project_name: amflow

before:
  hooks:
  - make clean
  - make frontend

builds:
- ldflags:
  - -s -w -X github.com/artefactual-labs/amflow/internal/version.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

dockers:
- goos: linux
  goarch: amd64
  dockerfile: Dockerfile.release
  image_templates:
  - "artefactual/amflow:latest"
  - "artefactual/amflow:v{{ .Major }}"
  - "artefactual/amflow:{{ .Tag }}"
  - "ghcr.io/artefactual-labs/amflow/amflow:latest"
  - "ghcr.io/artefactual-labs/amflow/amflow:v{{ .Major }}"
  - "ghcr.io/artefactual-labs/amflow/amflow:{{ .Tag }}"
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.vendor=Artefactual Systems Inc."
  - "--label=org.opencontainers.image.description=amflow {{.Tag}}"
  - "--label=org.opencontainers.image.url=https://github.com/artefactual-labs/amflow"
  - "--label=org.opencontainers.image.documentation=https://github.com/artefactual-labs/amflow/blob/main/README.md"
  - "--label=org.opencontainers.image.source=https://github.com/artefactual-labs/amflow"
  - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.created={{.Date}}"
