// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "amflow": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/sevein/amflow/design
// --out=/home/jesus/Projects/amflow/internal/api
// --version=v1.3.1

package test
