// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "amflow": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/artefactual-labs/amflow/design
// --out=/Users/jesus/amflow/internal/api
// --version=v1.3.1

package test
