name: Nightly

on:
  workflow_dispatch: {}
  schedule:
    # Daily, at 1pm UTC / 6am PST.
    - cron: "0 13 * * *"

jobs:
  govulncheck:
    name: Go vulnerability check
    runs-on: ubuntu-22.04
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          repo-checkout: true
          go-version-file: go.mod
