on:
  push:
    tags:
      - 'v*'
name: GoReleaser
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch all tags
      run: git fetch origin +refs/tags/*:refs/tags/*
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Install Docker credentials
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker login -u qubot -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.QUBOT_GITHUB_TOKEN }}
      if: success()
