// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "amflow": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/sevein/amflow/design
// --out=/home/jesus/Projects/amflow/internal/api
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// WorkflowHref returns the resource href.
func WorkflowHref(workflowID interface{}) string {
	paramworkflowID := strings.TrimLeftFunc(fmt.Sprintf("%v", workflowID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/workflow/%v", paramworkflowID)
}
