// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "amflow": Application User Types
//
// Command:
// $ goagen
// --design=github.com/artefactual-labs/amflow/design
// --out=/home/jesus/Projects/amflow/internal/api
// --version=v1.4.3

package app
